export default function Head() {
  return (
    <>
      <title>Gaqno Development</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by Gabriel Aquino" />
      <link rel="icon" href="/favicon.ico" />
    </> 
  )
}